language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest pytest-cov
script:
  - pytest --cov=./ tests/
after_success:
  - codecov