language: python
python:
  - "3.6"
cache: pip3
install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install pytest pytest-cov
script:
  - travis_wait 30 pytest --cov=./ -v
after_success:
  - codecov
